/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ExchangeLibraryInterface extends utils.Interface {
  contractName: "ExchangeLibrary";
  functions: {
    "getShortBaycAmountOut(uint256,uint256,uint256)": FunctionFragment;
    "getShortVusdAmountOut(uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getShortBaycAmountOut",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShortVusdAmountOut",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getShortBaycAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShortVusdAmountOut",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ExchangeLibrary extends BaseContract {
  contractName: "ExchangeLibrary";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ExchangeLibraryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getShortBaycAmountOut(
      _vUsdAmount: BigNumberish,
      vBaycPoolSize: BigNumberish,
      vUsdPoolSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getShortVusdAmountOut(
      _vBaycAmount: BigNumberish,
      vBaycPoolSize: BigNumberish,
      vUsdPoolSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getShortBaycAmountOut(
    _vUsdAmount: BigNumberish,
    vBaycPoolSize: BigNumberish,
    vUsdPoolSize: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getShortVusdAmountOut(
    _vBaycAmount: BigNumberish,
    vBaycPoolSize: BigNumberish,
    vUsdPoolSize: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getShortBaycAmountOut(
      _vUsdAmount: BigNumberish,
      vBaycPoolSize: BigNumberish,
      vUsdPoolSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getShortVusdAmountOut(
      _vBaycAmount: BigNumberish,
      vBaycPoolSize: BigNumberish,
      vUsdPoolSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getShortBaycAmountOut(
      _vUsdAmount: BigNumberish,
      vBaycPoolSize: BigNumberish,
      vUsdPoolSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getShortVusdAmountOut(
      _vBaycAmount: BigNumberish,
      vBaycPoolSize: BigNumberish,
      vUsdPoolSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getShortBaycAmountOut(
      _vUsdAmount: BigNumberish,
      vBaycPoolSize: BigNumberish,
      vUsdPoolSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getShortVusdAmountOut(
      _vBaycAmount: BigNumberish,
      vBaycPoolSize: BigNumberish,
      vUsdPoolSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
